config/routes.rb
Rails.application.routes.draw do
  resources :business_hours
  resources :rates
  resources :fields
  resources :games do
    member do
      post :join
      post :quit
    end
  end
  resources :categories
  resources :chains
  resources :pictures
  resources :centers
  resources :terrains
  resources :matches

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  root 'home#index'
  get 'home/about'
  get 'home/calendar'

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

end

app/models/center.rb
class Center < ActiveRecord::Base
  has_many :pictures, as: :imageable, :dependent => :destroy
  belongs_to :user
  belongs_to :chain
  has_many :fields, :dependent => :destroy
  has_many :categories, :dependent => :destroy
  has_many :business_hours, as: :bh, :dependent => :destroy

end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  before_action :set_center, only: [:show, :edit, :update, :destroy]

  # GET /centers
  # GET /centers.json
  def index
    @centers = Center.all
  end

  # GET /centers/1
  # GET /centers/1.json
  def show
  end

  # GET /centers/new
  def new
    @center = Center.new
  end

  # GET /centers/1/edit
  def edit
  end

  # POST /centers
  # POST /centers.json
  def create
    @center = Center.new(center_params)


    respond_to do |format|
      if @center.save

        if params[:images]
          params[:images].each do |image|
            @center.pictures.create(image: image)
          end
        end


        format.html { redirect_to @center, notice: 'Center was successfully created.' }
        format.json { render :show, status: :created, location: @center }
      else
        format.html { render :new }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centers/1
  # PATCH/PUT /centers/1.json
  def update
    respond_to do |format|
      if @center.update(center_params)

        if params[:images]
          params[:images].each do |image|
            @center.pictures.create(image: image)
          end
        end

        format.html { redirect_to @center, notice: 'Center was successfully updated.' }
        format.json { render :show, status: :ok, location: @center }
      else
        format.html { render :edit }
        format.json { render json: @center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centers/1
  # DELETE /centers/1.json
  def destroy
    @center.destroy
    respond_to do |format|
      format.html { redirect_to centers_url, notice: 'Center was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_center
      @center = Center.find(params[:id])

      ### Pictures ###
      default_pic = Picture.find_by_description('default-pic')
      @logo = @center.pictures.find_by_description('logo')
      @cover = @center.pictures.find_by_description('cover')
      @pic1 = @center.pictures.find_by_description('pic1')
      @pic2 = @center.pictures.find_by_description('pic2')
      @pic3 = @center.pictures.find_by_description('pic3')

      # addign default_pic if @var don't have a picture
      # still need to test if pic.nil ? in case default_pic doesnt exist
      @logo ||= default_pic
      @cover ||= default_pic
      @pic1 ||= default_pic
      @pic2 ||= default_pic
      @pic3 ||= default_pic

      ### Fields ###
      @fields = @center.fields.all

      ### Categories ###
      @categories = @center.categories.all
      @categories.each do |cat|
        cat.picture ||= default_pic
      end

      ### Game ###
      @game = Game.new

      ### Chain ###
      # @chain = @center.chain

      ### Owner ###
      # @owner = @center.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def center_params
      params.require(:center).permit(:pictures, :name, :status, :address, :country, :gmaps, :latitude, :longitude, :email, :phone_number, :description)
    end
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/views/centers/_form.html.erb
<%= form_for @center, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
  <% if @center.errors.any? %> 
    <div id="error_explanation">
      <h2><%= pluralize(@center.errors.count, "error") %> prohibited this center from being saved:</h2>

      <ul>
      <% @center.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br>
    <%= f.text_field :gmaps %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

<div class="control-group">
  <%= f.label :pictures, :class => 'control-label' %>
  <div class='control'>
    <!-- Use HTML5 multiple attribute to enable multiple selection
           and pass back to controller all files as an array, ready
           for paperclip!!
           file_field_tag, since images is not a center attribute
       -->
        <%= file_field_tag "images[]", type: :file, multiple: true %>
  </div>
</div>


  <div class="actions">
    <%= f.submit %>
  </div>

  <% unless @center.new_record? %>
    <div>
    <table>
    	<thead>
    	   <tr>
      		<th>Categorie</th>
      		<th>Description</th>
      		<th>Logo</th>
      		<th>Edit</th>
    	   </tr>
    	</thead>
    	<tbody>
    	   <% @center.categories.each do |cat| %>
          <tr>
          	<td><%= cat.name %></td>
          	<td><%= cat.description %></td>
            <td> <%= link_to image_tag(cat.picture.image.url(:medium)), cat.picture  %> </td>
          	<td><%= link_to "Modifier", edit_category_path(cat.id) %>	</td>
          </tr>
    	  <%end%>
      </tbody>
    </table>
    <%= link_to "Créer une nouvelle catégorie pour ce centre", new_category_path(center_id: @center.id) %>
    </div>

    <div>
    <table>
      <thead>
        <tr>
          <th>Terrains</th>
          <th>Description</th>
          <th>Categorie</th>
          <th>Statut</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        <% @center.fields.each do |field| %>
          <tr>
            <td><%= field.name %></td>
            <td><%= field.description %></td>
            <td><%= field.category.name %></td>
            <td><%= field.status.to_s %></td>
            <td><%= link_to "Modifier", edit_field_path(field.id) %>	</td>
          </tr>
        <%end%>
      </tbody>
    </table>
    <%= link_to "Créer un nouveau terrain pour ce centre", new_field_path(center_id: @center.id) %>
    </div>
    <div>
    <table>
    	<thead>
    	  <tr>
      		<th>Jour</th>
      		<th>Ouverture</th>
      		<th>Fermeture</th>
      		<th>Ouvert</th>
      		<th>Edit</th>
    	  </tr>
    	</thead>
    	<tbody>
    	   <% @center.business_hours.each do |bh| %>
          <tr>
          	<td><%= bh.day %></td>
          	<td><%= bh.start.strftime("%H:%M") %></td>
          	<td><%= bh.end.strftime("%H:%M") %></td>
          	<td><%= bh.open.to_s %></td>
          	<td><%= link_to "Modifier", edit_business_hour_path(bh.id) %>	</td>
          </tr>
    	  <%end%>
      </tbody>
    <table>
    <p>	<%= link_to 'Créer business hour', new_business_hour_path(bh_id: @center.id, bh_type: @center.class.name) %></p>
    </div>
  <% end %>

<% end %>

app/views/centers/_new_game_form.html.erb
<% # Desktop view %>
<div class="book-box" id="book-box">

<% if false %>
<% # Comments %>
  <% # @game.max_player = 10 %>
  <%= simple_form_for @game do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <% # TODO name = center + field + date + user %>
      <%= f.input :name %>
      <% # TODO day = datepicker %>
      <%= f.input :day %>
      <% # TODO start = dropdown %>
      <%= f.input :start %>
      <% # TODO end = start + duration (defautl 1h) %>
      <%= f.input :end %>
      <% # TODO price %>
      <% if false %>
      #  rate = category + day + start + end
      #
      #  category = dropdown menu
      #  day = datepicker
      #  category.rate where day = day
      #  and category.rate where  category.rate.start < start < category.rate.end
      #        later if game   end category.rate =! start cartery.rate ...
      #  duration = end - start
      #  rate * duration = price
      #  price / max_player = price per player
      #<%end%>
      <%= f.input :price%>
      <% #  ? class not working without:  , {}, {class: ''} %>
      <label class="select-field">
        <%=f.select :max_player, options_for_select([['8 joueurs', 8], ['10 joueurs', 10],['12 joueurs', 12]],10),
                                {}, {class: 'book-box-select-field'} %>
      </label>
      <% # No using now %>
      <% f.input :max_substitute %>
      <% f.input :payment %>
      <% f.input :status %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

<% # end comments %>
<%end%>

    <% # Desktop form %>
    <form>
        <label class="icon-calendar booking-input">
            <% # TODO A enregistrer pour game.date %>
            <input type="text" id="datepicker"
                    class="book-box-datepicker"
                    name="datepicker" placeholder="Date" />
        </label>
        <label class="icon-clock booking-input sm-margin-top">
            <% # TODO A enregistrer pour game.start %>
            <input type="text" id="timepicker"
                    class="book-box-timepicker"
                    name="timepicker" placeholder="Horaire" />
        </label>
        <label class="select-field sm-margin-top">
            <select class="book-box-select-field">
                <% unless @categories.nil? %>
                  <% @categories.each do |cat| %>
                  <option value= "<%= cat.name.to_s %>" > Terrain
                  <%= cat.description.to_s %></option>
                  <%end%>
                <%end%>
            </select>
        </label>
        <div class="sm-margin-top">
          <div class="collapse" id="more-option-booking">
            <label class="select-field">
                <select class="book-box-select-field">
                  <% # TODO A afficher en fonction de ? %>
                  <% # TODO A enregistrer pour game.max_player %>
                    <option value="eight-players">8 joueurs</option>
                    <option value="ten-players" selected>10 joueurs</option>
                    <option value="twelve-players">12 joueurs</option>
                </select>
            </label>
            <label class="select-field sm-margin-top">
              <select class="book-box-select-field">
                <% # TODO A afficher en fonction des créneaux dispo %>
                <% # TODO A enregistrer pour game.end %>
                <option value="60">60 minutes</option>
                <option value="90">90 minutes</option>
                <option value="120">120 minutes</option>
              </select>
            </label>
          </div>
            <a class="more-option-button" id="more-option-button" role="button" data-toggle="collapse"
                href="#more-option-booking" aria-expanded="false" aria-controls="more-option-booking">
                Plus d'options
            </a>
          </div>
          <% # TODO A afficher en fonction du prix pour le terrain à l'heure choisie%>
          <% # TODO A enregistrer pour game.price %>
          <h3><b>8€ par joueur(?)</b></h3>
          <p>(8€ x 10 joueurs = 80€)(?)</p>
          <button id="submit-location" type="submit" class="btn-lg btn-book btn-block sm-margin-top">
          <i class="fa fa-bolt"></i>&nbsp;&nbsp;Réservation instantannée 8€</button>
    </form>
</div>

<% # Mobile view %>
<div class="booking-bar-responsive-container" id="booking-bar-responsive">
    <div class="booking-bar-responsive">
        <% # Button to open mobile view reservation %>
        <span><i class="fa fa-bolt"></i>&nbsp;&nbsp;Réservation instantannée</span>
    </div>
</div>
<div class="booking-modal">
    <div class="booking-modal-header">
        <button id="close-booking-modal" class="close"><span>&times;</span></button>
        <% # Page title %>
        <h4 class="modal-title text-center">Réservation instantannée</h4>
    </div>
    <div class="modal-body">
        <% unless @logo.nil? %>
          <%= image_tag(@logo.image.url(:medium), class:"field-logo sm-margin-top") %>
        <%end%>
        <h2 class="text-center"><%= @center.name %></h2>
        <p class="text-center"><%= @center.address %></p>

        <% # Mobile form %>
        <div class="booking-form-responsive">
            <form>
                <div class="row">
                    <% # Date %>
                    <label class="sm-margin-top">
                        <input type="text" id="datepicker-responsive"
                                class="search-bar-datetimepicker-responsive"
                                name="datepicker" placeholder="Date" />
                    </label>
                    <% # Time %>
                    <label class="sm-margin-top">
                        <input type="text" id="timepicker-responsive"
                                class="search-bar-datetimepicker-responsive xs-margin-left"
                                name="timepicker" placeholder="Horaire" />
                    </label>
                </div>
                <% # Category %>
                <label class="select-field">
                    <select class="book-box-select-field">
                      <% unless @categories.nil? %>
                        <% @categories.each do |cat| %>
                        <option value= "<%= cat.name.to_s %>" > Terrain
                        <%= cat.description.to_s %></option>
                        <%end%>
                      <%end%>
                    </select>
                </label>
                <% # Submit button %>
                <button id="submit-location" type="submit"
                        class="btn-lg btn-block btn-booking-responsive sm-margin-top">
                  <i class="fa fa-bolt"></i>&nbsp;&nbsp;Réserver maintenant</button>
            </form>
        </div>
    </div><!-- End modal body -->
</div><!-- End modal -->

app/views/centers/edit.html.erb
<h1>Editing Center</h1>

<%= render 'form' %>

<%= link_to 'Show', @center %> |
<%= link_to 'Back', centers_path %>

app/views/centers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Centers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Address</th>
      <th>Country</th>
      <th>Gmaps</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @centers.each do |center| %>
      <tr>
        <td><%= center.name %></td>
        <td><%= center.status %></td>
        <td><%= center.address %></td>
        <td><%= center.country %></td>
        <td><%= center.gmaps %></td>
        <td><%= center.latitude %></td>
        <td><%= center.longitude %></td>
        <td><%= center.email %></td>
        <td><%= center.phone_number %></td>
        <td><%= center.description %></td>
        <td><%= link_to 'Show', center %></td>
        <td><%= link_to 'Edit', edit_center_path(center) %></td>
        <td><%= link_to 'Destroy', center, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Center', new_center_path %>

app/views/centers/new.html.erb
<h1>New Center</h1>

<%= render 'form' %>

<%= link_to 'Back', centers_path %>

app/views/centers/show.html.erb
<div class="container-fluid">
    <section class="summary-field-section">
        <div class="container">
            <div class="col-lg-8 sm-padding-top xs-padding-bottom">
                <div class="row">
                    <div class="col-sm-2">
                      <% unless @logo.nil? %>
                      <%= image_tag(@logo.image.url(:medium), class:"field-logo") %>
                      <%end%>
                    </div>
                    <div class="col-sm-10">
                        <h2><%= @center.name %></h2>
                        <p><%= @center.address %></p>
                        <div class="row">
                          <% @categories.each do |cat| %>
                          <div class="col-sm-3 col-xs-4 text-center">
                              <% unless cat.picture.nil? %>
                                <%=  image_tag(cat.picture.image.url(:thumb), class:"field-type-icon") %>
                                <% if (cat.fields.count) == 1 %>
                                  <p><%= cat.fields.count.to_s %> terrain <%= cat.description %></p>
                                <%else%>
                                  <p><%= cat.fields.count.to_s %> terrains <%= cat.description %></p>
                                <%end%>
                              <%end%>
                          </div>
                          <% end %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 no-padding">
              <%= render 'new_game_form' %>
            </div><!-- End col-lg-4 -->
        </div> <!-- End container -->
    </section>
    <section class="field-description">
        <div class="container">
            <div class="col-lg-8">
                <% unless @cover.nil? %>
                <%= image_tag(@cover.image.url(), class:"img-thumbnail-field-main no-border-top") %>
                <%end%>
                <div class="row no-margin">
                    <div class="col-xs-4 no-padding">
                        <% unless @pic1.nil? %>
                        <%= image_tag(@pic1.image.url(:medium), class:"img-responsive img-thumbnail-field") %>
                        <%end%>
                    </div>
                    <div class="col-xs-4 no-padding">
                      <% unless @pic2.nil? %>
                      <%= image_tag(@pic2.image.url(:medium), class:"img-responsive img-thumbnail-field") %>
                      <%end%>
                    </div>
                    <div class="col-xs-4 no-padding">
                      <% unless @pic3.nil? %>
                        <%= image_tag(@pic3.image.url(:medium), class:"img-responsive img-thumbnail-field") %>
                      <%end%>
                    </div>
                </div>
                <h3 class="md-margin-top sm-margin-bottom">À propos de ce centre</h3>
                <p><%= @center.description%> </p>
                <hr class="divider-field-section">
                <div class="row">
                    <div class="col-sm-3">
                        <span class="light-grey">Le centre</span>
                    </div>
                    <div class="col-sm-9">
                        <div class="row">
                            <div class="col-sm-6">
                              <% unless @categories.nil? %>
                                  <% @categories.each do |cat| %>
                                    <% unless cat.fields.empty? %>
                                      <% if (cat.fields.count) == 1 %>
                                        <span class="normal-grey">Terrain <%= cat.description %> :
                                        <span class="dark-grey"><%= cat.fields.count.to_s %> </span></span><br>
                                      <%else%>
                                        <span class="normal-grey">Terrains <%= cat.description %> :
                                        <span class="dark-grey"><%= cat.fields.count.to_s %> </span></span><br>
                                      <%end%>
                                    <%end%>
                                  <%end%>
                                <%end%>
                                <p> Un peu redondant avec le début où on a les types de terrain avec les icones </p>
                            </div>
                            <div class="col-sm-6">
                                <% # TODO center/description à modifier pour faire un array  %>
                                <span class="normal-grey">Vestiaires privés(?)</span><br>
                                <span class="normal-grey">Parking gratuit(?)</span><br>
                                <span class="normal-grey">Buvette(?)</span>
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="divider-field-section">
                <div class="row">
                    <div class="col-sm-3">
                        <span class="light-grey">Prix</span>
                    </div>
                    <div class="col-sm-9">
                        <div class="rowcategories" >
                            <div class="col-sm-6">
                              <% unless @categories.nil? %>
                                  <% @categories.each do |cat| %>
                                    <% unless cat.rates.empty?  %>
                                      <% max_rate = cat.rates.order('hourly_rate DESC').first.hourly_rate.to_i%>
                                      <% min_rate = cat.rates.order('hourly_rate DESC').last.hourly_rate.to_i%>
                                      <span class="normal-grey">Terrain <%=cat.name %>:
                                      <span class="dark-grey"><%= "#{min_rate}-#{max_rate} €" %>
                                      </span></span><br>
                                    <%end%>
                                  <%end%>
                              <%end%>
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="divider-field-section">
                <div class="row">
                    <div class="col-sm-3">
                        <span class="light-grey">Conditions<br>d'annulation</span>
                    </div>
                    <div class="col-sm-9">
                        <div class="row">
                            <div class="col-sm-12">
                                <% # TODO Condition d'annulation a recuperer %>
                                <span class="normal-grey">Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                  Aenean commodo sem dapibus viverra sodales. Aliquam suscipit arcu mi(?)</span>
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="divider-field-section">
                <div class="row" id="contact">
                    <div class="col-sm-3">
                        <span class="light-grey">Contact</span>
                    </div>
                    <div class="col-sm-9">
                        <div class="row">
                            <div class="col-xs-1 text-center no-padding">
                                <i class="fa fa-phone dark-grey"></i><br>
                                <i class="fa fa-envelope-o dark-grey"></i><br>
                                <i class="fa fa-map-marker dark-grey"></i><br>
                            </div>
                            <div class="col-xs-11 no-padding">
                                <span class="normal-grey"> <%= @center.phone_number %></span><br>
                                <span class="normal-grey"> <%= @center.email %></span><br>
                                <span class="normal-grey"> <%= @center.address %></span>
                            </div>
                        </div>
                    </div>
                </div><!-- End row contact -->

                <div class="embed-responsive embed-responsive-16by9 lg-margin-top lg-margin-bottom" id="gmap">
                    <!-- A modifier, utiliser API JS Google -->
                    <% # TODO A modifer - @center.gmap true + @center.latitude + @center.longitude %>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2626.994762026785!2d2.391422315643344!3d48.820161379283746!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6724c27587c7d%3A0xe19e10c2037f459b!2s14+Rue+Jules+Vanzuppe%2C+94200+Ivry-sur-Seine%2C+France!5e0!3m2!1sfr!2ses!4v1449080409833" width="800" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>

            </div><!-- End col-lg-8 -->
        </div><!-- End container -->
    </section>
</div>



<%= link_to 'Edit', edit_center_path(@center) %> |
<%= link_to 'Back', centers_path %>