config/routes.rb
Rails.application.routes.draw do
  resources :business_hours
  resources :rates
  resources :fields
  resources :games do
    member do
      post :join
      post :quit
    end
  end
  resources :categories
  resources :chains
  resources :pictures
  resources :centers
  resources :terrains
  resources :matches

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  root 'home#index'
  get 'home/about'
  get 'home/calendar'

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :field
  has_many :reservations
  has_many :users, through: :reservations
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :join, :quit]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        create_reservation(current_user, 'captain')

        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def join
    if  create_reservation(current_user, 'player')
      redirect_to @game, notice: 'You join the game'
    else redirect_to @game, notice: 'cannot join the game'
    end
  end

  def quit
    delete_reservation(current_user)
    redirect_to @game, notice: 'You quit the game'
  end


  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])

      if @game.reservations.any?
        # Captain = the one who create the game
        @captain = @game.reservations.find_by_status('captain').user
        # reservations of users who had confirmed
        @res_players = @game.reservations.where(status: 'player')

        @user_belongs_to_game = false
        @game.users.each do |user|
           if user.id == current_user.id
            @user_belongs_to_game = true
          end
        end

      end
    end

    def create_reservation(user, status)
      reservation = Reservation.create(game: @game, user: user, status: status)
    end

    def delete_reservation(user)
      Reservation.where(game_id: @game.id, user_id: user).first.destroy
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :day, :start, :end, :price, :max_player, :max_substitute, :payment, :status)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :day %>
    <%= f.input :start %>
    <%= f.input :end %>
    <%= f.input :price %>
    <%= f.input :max_player %>
    <%= f.input :max_substitute %>
    <%= f.input :payment %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/_list_players.html.erb
<div class="row">
  <% # TODO image url instead of picture ?? - user has_one picture  %>
  <% if @game.reservations %>

    <% # Captain first %>
    <% if @game.reservations.find_by_status('captain') %>
      <div class="col-md-2  col-xs-6">
        <div class="thumbnail-player"  title="Captain">
          <% if @captain.image %>
            <%= image_tag(@captain.image.url(:thumb), class:"player-picture") %>
            <i class="fa fa-check-circle fa-2x"></i>
          <%end%>
          <div class="player-name"><%= @captain.first_name %> <%= @captain.last_name %></div>
        </div>
      </div>
    <%end%>

    <% # List of users playing %>
    <% if @res_players %>
      <% @res_players.each do |res| %>
        <div class="col-md-2  col-xs-6">
          <div class="thumbnail-player"  title="Joueur présent">
            <% if res.user.image %>
            <%= image_tag(res.user.image.url(), class:"player-picture") %>
            <i class="fa fa-check-circle fa-2x"></i>
            <%end%>
            <div class="player-name"><%= res.user.first_name %> <%= res.user.last_name %></div>
          </div>
        </div>
      <%end%>
    <%end%>

  <%end%>

  <% # Add an player %>
  <% # 1 = captain  %>
  <% if @res_players && (@res_players.count + 1) < @game.max_player.to_i %>
  <div class="col-md-2 col-xs-6">
    <div class="thumbnail-player" title="Ajouter un joueur">
      <% # TODO Add invit link %>
      <%= link_to "<button class='player-picture add-player'><i class='fa fa-user fa-3x'></i><i class='fa fa-plus-circle fa-2x'></i></button>".html_safe,
          root_path, :id => "button_id"%>
    <span class="player-name">Ajouter un joueur</span>
  </div>
  </div>
  <%end%>

  <% # empty space %>
  <% # 2 = captain & add player button %>
  <% if @res_players %>
  <% available_place = (@game.max_player.to_i - @res_players.count - 2) %>
  <%else%>
  <% available_place = (@game.max_player.to_i - 2) %>
  <%end%>
  <% if available_place < 0 %> <%available_place = 0%> <%end%>
  <% for i in 1..available_place do %>
    <div class="col-md-2 col-xs-6">
      <div class="thumbnail-player" title="Place libre">
        <div class="player-picture player-empty"><i class="fa fa-user fa-3x"></i></div>
        <span class="player-name-empty">Place libre</span>
      </div>
    </div>
    <% end %>
</div>

app/views/games/_more_info_center.html.erb
<% if @game.field && @game.field.center %>
<div class="modal fade" id="details-field-modal" tabindex="-1" role="dialog" aria-labelledby="details-field-modal-label">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="details-field-modal-label"><%= @game.field.center.name %> - <%= @game.field.center.address %></h4>
      </div>
      <div class="modal-body">
        <div class="media col-md-10 xs-padding-top">
          <div class="media-left media-middle">
            <% if @game.field.center.pictures.find_by_description('logo') %>
            <%= image_tag(@game.field.center.pictures.find_by_description('logo').image.url(:thumb), class:"field-logo") %>
            <%end%>
          </div>
          <div class="media-body sm-padding-left">
            <h2 class="media-heading"><%= @game.field.center.name %></h2>
            <p><%= @game.field.center.address %></p>
              <div class="row">
                <% if @game.field.center.categories %>
                <% @game.field.center.categories.each do |cat| %>
                <div class="col-sm-3 col-xs-4 text-center">
                    <% if cat.picture %>
                      <%=  image_tag(cat.picture.image.url(:thumb), class:"field-type-icon") %>
                      <% if (cat.fields.count) == 1 %>
                        <p><%= cat.fields.count.to_s %> terrain <%= cat.description %></p>
                      <%else%>
                        <p><%= cat.fields.count.to_s %> terrains <%= cat.description %></p>
                      <%end%>
                    <%end%>
                </div>
                <%end%>
                <%end%>
              </div>
          </div>
        </div>

        <div class="row">
          <% if @game.field.center.pictures.find_by_description('cover') %>
          <%= image_tag(@game.field.center.pictures.find_by_description('cover').image.url(), class:"img-thumbnail-field-main no-border-top") %>
          <%end%>
        </div>

        <div class="xs-padding">
          <h4><b>À propos de ce centre</b></h4>
          <%=@game.field.center.description%>
          <div class="row">
            <div class="col-sm-3">
              <span class="light-grey">Le centre</span>
            </div>
            <div class="col-sm-9">
              <div class="row">
                <div class="col-sm-6">
                  <% if @game.field.center.categories %>
                      <% @game.field.center.categories.each do |cat| %>
                        <% unless cat.fields.empty? %>
                          <% if (cat.fields.count) == 1 %>
                            <span class="normal-grey">Terrain <%= cat.description %> :
                            <span class="dark-grey"><%= cat.fields.count.to_s %> </span></span><br>
                          <%else%>
                            <span class="normal-grey">Terrains <%= cat.description %> :
                            <span class="dark-grey"><%= cat.fields.count.to_s %> </span></span><br>
                          <%end%>
                        <%end%>
                      <%end%>
                    <%end%>
                    <p> Un peu redondant avec le début où on a les types de terrain avec les icones </p>
                </div>
                <div class="col-sm-6">
                    <% # TODO center/description à modifier pour faire un array  %>
                    <span class="normal-grey">Vestiaires privés(?)</span><br>
                    <span class="normal-grey">Parking gratuit(?)</span><br>
                    <span class="normal-grey">Buvette(?)</span>
                </div>
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <span class="light-grey">Prix</span>
            </div>
            <div class="col-sm-9">
              <div class="row">
                <div class="col-sm-6">
                  <% if @game.field.center.categories %>
                      <% @game.field.center.categories.each do |cat| %>
                        <% unless cat.rates.empty?  %>
                          <% max_rate = cat.rates.order('hourly_rate DESC').first.hourly_rate.to_i%>
                          <% min_rate = cat.rates.order('hourly_rate DESC').last.hourly_rate.to_i%>
                          <span class="normal-grey">Terrain <%=cat.name %>:
                          <span class="dark-grey"><%= "#{min_rate}-#{max_rate} €" %>
                          </span></span><br>
                        <%end%>
                      <%end%>
                  <%end%>
                </div>
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <span class="light-grey">Conditions<br>d'annulation</span>
            </div>
            <div class="col-sm-9">
              <div class="row">
                <div class="col-sm-12">
                  <% # TODO %>
                  <span class="normal-grey">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean commodo sem dapibus viverra sodales. Aliquam suscipit arcu mi, at vulputate tortor posuere nec. Duis ultricies vestibulum lorem, nec mollis massa iaculis id. Etiam in feugiat nisi.</span>
                </div>
              </div>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-sm-3">
              <span class="light-grey">Contact</span>
            </div>
            <div class="col-sm-9">
              <div class="row">
                <div class="col-xs-1 text-center no-padding">
                  <i class="fa fa-phone dark-grey"></i><br>
                  <i class="fa fa-envelope-o dark-grey"></i><br>
                  <i class="fa fa-map-marker dark-grey"></i>
                </div>
                <div class="col-xs-11 no-padding">
                  <span class="normal-grey"> <%= @game.field.center.phone_number %></span><br>
                  <span class="normal-grey"> <%= @game.field.center.email %></span><br>
                  <span class="normal-grey"> <%= @game.field.center.address %></span>
                </div>
              </div>
            </div>
          </div><!-- End row contact -->

          <div class="embed-responsive embed-responsive-16by9 md-margin-top">
            <% # TODO Gmap %>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2626.994762026785!2d2.391422315643344!3d48.820161379283746!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6724c27587c7d%3A0xe19e10c2037f459b!2s14+Rue+Jules+Vanzuppe%2C+94200+Ivry-sur-Seine%2C+France!5e0!3m2!1sfr!2ses!4v1449080409833" width="800" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
          </div>
        </div>

      </div>
    </div>
    </div>
</div>
<%end%>

app/views/games/edit.html.erb
<% if false %>
	<h1>Editing Game</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @game %> |
	<%= link_to 'Back', games_path %>
	
<%end%>


<div class="container-fluid">
	<section class="match-description">
		<div class="container">
			<div class="row">
				<div class="col-sm-3 no-padding">
					<ul class="side-nav nav nav-tabs" role="tablist">
						<li class="active">
							<%= link_to "Modifier la réservation", edit_game_path(@game) %>
						</li>
						<li><%= link_to "Annuler la réservation", edit_game_path(@game) %></li>
						<li><%= link_to "Retour au match", @game %></li>
					</ul>
				</div>
				<div class="col-sm-9 no-padding">
					<form method="get">	
						<div class="box-configuration no-padding">
							<div class="box-match-description-header">Modifier la réservation</div>
							<div class="box-match-description-body">
								<span class="normal-grey"><b><i class="fa fa-exclamation-circle"></i>  Attention:</b> modifier certaines options peut changer le prix de la réservation et donc le prix à payer par joueur.</span>
								<div class="row sm-margin-top">
									<label class="col-xs-3 text-right" for="datepicker"><b>Date du match</b></label>
									<div class="col-xs-9">
										<label class="icon-calendar booking-input">
											<input type="text" id="datepicker" class="book-box-datepicker" name="datepicker" placeholder="Date" />
										</label>
									</div>
								</div>
								<div class="row sm-margin-top">
									<label class="col-xs-3 text-right" for="timepicker"><b>Horaire du match</b></label>
									<div class="col-xs-9">
										<label class="icon-clock booking-input">
											<input type="text" id="timepicker" class="book-box-timepicker" name="timepicker" placeholder="Horaire" />
										</label>
									</div>
								</div>
								<div class="row sm-margin-top">
									<label class="col-xs-3 normal-grey text-right"><b>Durée du match</b></label>
									<div class="col-xs-9">
										<label class="select-field"> 
											<select class="book-box-select-field">
												<option value="60">60 minutes</option>
												<option value="90">90 minutes</option>
												<option value="120">120 minutes</option>
											</select>
										</label>
									</div>
								</div>
								<div class="row sm-margin-top">
									<label class="col-xs-3 text-right"><b>Nombre de joueurs</b></label>
									<div class="col-xs-9 set-number-players">
										<div class="row no-padding">
											<label class="col-xs-4">
												<input type="radio" id="eight-players" name="number-players" /><label for="eight-players"><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i>&nbsp;&nbsp;8 (4 vs 4)</label>
											</label>
											<label class="col-xs-4">
												<input type="radio" id="ten-players" name="number-players" checked /><label for="ten-players"><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i>&nbsp;&nbsp;10 (5 vs 5)</label>
											</label>
											<label class="col-xs-4">
												<input type="radio" id="twelve-players" name="number-players" /><label for="twelve-players"><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i>&nbsp;&nbsp;12 (6 vs 6)</label>
											</label>
										</div>
										<div class="xs-margin-top">
											<div class="collapse row no-padding" id="more-option-players">
												<label class="col-xs-4">
													<input type="radio" id="nine-players" name="number-players" /><label for="nine-players"><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i>&nbsp;&nbsp;9 (5 vs 4)</label>
												</label>
												<label class="col-xs-4">
													<input type="radio" id="eleven-players" name="number-players" /><label for="eleven-players"><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i><i class="fa fa-user"></i>&nbsp;&nbsp;11 (6 vs 5)</label>
												</label>
											</div>
											<a class="more-option-button" id="more-option-button" role="button" data-toggle="collapse" href="#more-option-players" aria-expanded="false" aria-controls="more-option-players">Plus d'options</a>
										</div>
									</div>
								</div>
								<div class="row sm-margin-top">
									<label class="col-xs-3 text-right"><b>Type de terrain</b></label>
									<div class="col-xs-9">
										<label class="select-field"> 
											<select class="book-box-select-field">
												<option value="normal">Terrain normal</option>
												<option value="camera">Terrain avec caméra</option>
												<option value="prestige">Terrain prestige</option>
											</select>
										</label>
									</div>
								</div>
								<div class="row sm-margin-top">
									<label class="col-xs-3 text-right"><b>Prix total de la réservation</b></label>
									<div class="col-xs-9">80€</div>
								</div>
								<div class="row sm-margin-top">
									<label class="col-xs-3 text-right"><b>Prix par joueur</b></label>
									<div class="col-xs-9">8€ par joueur (10 joueurs x 8€ = 80€)</div>
								</div>
							</div>
						</div>
						<div class="box-configuration sm-margin-top no-padding">
							<div class="box-match-description-header">Paramètres liés au paiement</div>
							<div class="box-match-description-body">
								<div class="row">
									<label class="col-xs-3 text-right"><b>Répartition du paiement</b></label>
									<div class="col-xs-9">
										<div class="row">
											<div class="col-xs-6"><input type="radio" id="payment-repartition-each-player" name="payment-repartition" checked />
											<label for="payment-repartition-each-player">Chaque joueur paye sa part</label></div>
											<div class="col-xs-6"><input type="radio" id="payment-repartition-captain" name="payment-repartition" />
											<label for="payment-repartition-captain">Le capitaine paye pour tous les joueurs</label></div>
										</div>
									</div>
								</div>
								<div class="row sm-margin-top">
									<label class="col-xs-3 text-right"><b>Paiement par autre joueur</b></label>
									<div class="col-xs-9">
										<input type="checkbox" id="checkbox-invitation-players-authorization" checked /><label for="checkbox-invitation-players-authorization">Les joueurs peuvent payer pour inscrire d'autres joueurs</label>
									</div>
								</div>
							</div>
						</div>
						<button class="btn-save-configuration sm-margin-top" type="submit">Enregistrer</button>
					</form>
				</div>
			</div>
		</div>
	</section>
</div>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Day</th>
      <th>Start</th>
      <th>End</th>
      <th>Price</th>
      <th>Max player</th>
      <th>Max substitute</th>
      <th>Payment</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.day %></td>
        <td><%= game.start %></td>
        <td><%= game.end %></td>
        <td><%= game.price %></td>
        <td><%= game.max_player %></td>
        <td><%= game.max_substitute %></td>
        <td><%= game.payment %></td>
        <td><%= game.status %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Game', new_game_path %>
<%else%>
  <p>Veuillez vous connecter pour creer un match</p>
  <li><%= link_to "Se connecter", new_user_session_path %></li>
  <li><%= link_to "S'inscrire", new_user_registration_path %></li>
<%end%>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="container-fluid">
  <section class="booked-field">
    <div class="container">
      <div class="row">
        <div class="col-sm-1 col-sm-offset-2 col-xs-5 text-center no-padding">
          <div class="date-box" title="Date du match">
            <div class="date-month"> <%= @game.day.strftime("%^b")%></div>
            <div class="date-day"><%= @game.day.strftime("%d")%></div>
          </div>
        </div>
        <div class="col-sm-2 col-xs-7">
          <div class="row time-box" title="Horaire du match">
            <%= image_tag("clock-icon.png", class:"match-time-icon") %>
            <div class="match-time"><%= @game.start.strftime("%H:%M")%> - <%= @game.end.strftime("%H:%M")%></div>
          </div>
        </div>
        <div class="col-sm-6 col-xs-12 field-match-box" title="Lieu du match">
          <div class="media">
            <div class="media-left media-middle">
              <%if @game.field && @game.field.center && @game.field.center.pictures.find_by_description('logo') %>
              <%= image_tag(@game.field.center.pictures.find_by_description('logo').image.url(:thumb), class:"media-object") %>
              <%end%>
            </div>
            <div class="media-body xs-padding-left">
              <%if @game.field && @game.field.center%>
              <h4 class="field-match-name media-heading"><%= @game.field.center.name %></h4>
              <div class="field-match-adress"><%= @game.field.center.address %></div>
              <button class="btn-light-white xs-margin-top" data-toggle="modal" data-target="#details-field-modal">Plus d'information</button>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="match-description">
    <div class="container">
      <div class="row">
        <div class="col-sm-3 no-padding">
          <ul class="side-nav nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
              <%= link_to "Liste des joueurs", "#list-of-players", :role => "tab", :data => {:toggle => "tab"}, :aria => {:controls => "list-of-players"} %>
            </li>
            <li role="presentation">
              <%= link_to "Configuration du match", "#configuration", :role => "tab", :data => {:toggle => "tab"}, :aria => {:controls => "configuration"} %>
            </li>
            <li role="presentation">
              <%= link_to "Liste d'attente", "#waiting-list", :role => "tab", :data => {:toggle => "tab"}, :aria => {:controls => "waiting-list"} %>
            </li>
          </ul>
        </div>
        <div class="col-sm-9 no-padding tab-content">
          <div role="tabpanel" class="tab-pane active" id="list-of-players">
              <div class="box">
                <div class="box-header">Liste des joueurs</div>
                <div class="box-body">
                <%= render 'list_players'%>
                </div>
                <hr class="divider-box-match">
                <div class="box-footer">
                  <div class="row">
                    <div class="col-sm-2 col-sm-offset-2 col-xs-6">
                      <div class="guest-number-box">
                        <%if @res_players %>
                        <div class="guest-number"><%= "#{@res_players.count + 1}/#{@game.max_player.to_i}" %></div>
                        <%else%>
                        <div class="guest-number"><%= "1/#{@game.max_player.to_i}" %></div>
                        <%end%>
                        <div class="guest-subtitle">joueurs</div>
                      </div>
                    </div>
                    <% if false %>
                    <div class="col-sm-2 col-xs-6">
                      <div class="guest-number-box">
                        <% # TODO number of invit%>
                        <div class="guest-number">26</div>
                        <div class="guest-subtitle">invités</div>
                      </div>
                    </div>
                    <div class="col-sm-4 col-xs-12 text-center">
                      <% # TODO message to players%>
                      <button class="btn-light-white btn-send-message xs-margin-top">
                        <i class="fa fa-comment"></i>&nbsp;&nbsp;Message aux joueurs</button>
                    </div>
                    <%end%>
                    <div class="col-sm-4 col-xs-12 text-center">

                      <% unless @user_belongs_to_game %>
                      <%= link_to 'Rejoindre la partie', join_game_path(@game), method: :post%>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
          </div>
          <%= render 'options' %>
        </div>
      </div>
    </div>
  </section>

  <%= render 'more_info_center' %>

</div>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">

        <% # Facebook send button %>
        <% if Rails.env.development?%>
        <div class="fb-send" data-href="http://levestiaire.co"> </div></br>
        <%= link_to "Partager sur facebook", "https://www.facebook.com/sharer/sharer.php?u=http://levestiaire.co" %> </br>
        <% fb_send_url = "http://www.facebook.com/dialog/send?app_id=" + ENV['FACEBOOK_APP_ID'].to_s + "&link=" + "http://levestiaire.co" + "&redirect_uri=" + request.original_url.to_s %>
        <%= link_to "Envoyer sur facebook", fb_send_url %> </br>

        <%end%>
        <% if Rails.env.production?%>
        <div class="fb-send"> </div> </br>
        <% fb_share_url = "https://www.facebook.com/sharer/sharer.php?u=" + request.original_url.to_s %>
        <%= link_to "Partager sur facebook", fb_share_url %> </br>
        <% fb_send_url = "http://www.facebook.com/dialog/send?app_id=" + ENV['FACEBOOK_APP_ID'].to_s + "&link=" + request.original_url.to_s + "&redirect_uri=" + request.original_url.to_s %>
        <%= link_to "Envoyer sur facebook", fb_send_url %> </br>
        <%end%>

        <%= link_to 'Edit', edit_game_path(@game) %> |
        <%= link_to 'Back', games_path %>
      </div>
    </div>
  </div>
</div>