config/routes.rb
Rails.application.routes.draw do
  resources :business_hours
  resources :rates
  resources :fields
  resources :games do
    member do
      post :join
      post :quit
    end
  end
  resources :categories
  resources :chains
  resources :pictures
  resources :centers
  resources :terrains
  resources :matches

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  root 'home#index'
  get 'home/about'
  get 'home/calendar'

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :terrains
  has_many :fields
  has_one :picture, as: :imageable, :dependent => :destroy
  has_many :rates, :dependent => :destroy
  belongs_to :center
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_centers

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save

        if params[:image]
          @category.picture = Picture.new(image: params[:image])
        end


        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)

        if params[:image]
          @category.picture = Picture.new(image: params[:image])
        end

        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    def set_centers
      @centers = Center.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :center_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this chain from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if params[:center_id].present? %>
  <% @category.center_id = params[:center_id] %>
  <% end %>
  <div class="field">
    <%= f.label :center_id %></br>
    <%= f.collection_select(:center_id, @centers, :id, :name, :include_blank => "Choisir un centre") %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <% unless @category.picture.nil? %>
  <div> <%= link_to image_tag(@category.picture.image.url(:medium)), @category.picture  %> </div>
  <%end%>
  <div class="form-group">
    <%= f.label :picture %>
    <%= file_field_tag "image", type: :file %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Centre</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= category.center.name %></td>
        <% unless category.picture.nil? %>
        <td> <%= link_to image_tag(category.picture.image.url(:medium)), category.picture  %> </td>
        <%end%>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Centre:</strong>
  <%= @category.center.name %>
</p>

<% unless @category.picture.nil? %>
<p>
  <strong>Picture:</strong>
  <%= link_to image_tag(@category.picture.image.url(:medium)), @category.picture  %>
</p>

<%end%>

<table>
	<thead>
    <strong>Liste des taux horaires</strong>
	<tr>
		<th>Jour</th>
		<th>De</th>
		<th>Jusqu'à</th>
		<th>Prix à l'heure</th>
		<th>Edit</th>
	</tr>
	</thead>
	<tbody>
	<% @category.rates.each do |rate| %>
<tr>
	<td><%= rate.day %></td>
	<td><%= rate.start.strftime("%H:%M") %></td>
	<td><%= rate.end.strftime("%H:%M") %></td>
	<td><%= rate.hourly_rate %></td>
	<td><%= link_to "Modifier", edit_rate_path(rate.id) %>	</td>
</tr>
	<%end%>
</tbody>
<table>

<p>
  <%= link_to 'Ajouter un Rate', new_rate_path(category_id: @category.id) %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>