config/routes.rb
Rails.application.routes.draw do
  resources :business_hours
  resources :rates
  resources :fields
  resources :games do
    member do
      post :join
      post :quit
    end
  end
  resources :categories
  resources :chains
  resources :pictures
  resources :centers
  resources :terrains
  resources :matches

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  root 'home#index'
  get 'home/about'
  get 'home/calendar'

  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end

end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :center
  belongs_to :category
  has_many :games
  has_many :business_hours, as: :bh, :dependent => :destroy


end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:edit, :update]
  before_action :set_centers,

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    if params[:field][:center_id]
      @center = Center.find_by_id(params[:field][:center_id])
      @field = @center.fields.build(field_params)
    else
      @field = Field.new(field_params)
    end
    if params[:field][:category_id]
      @field.category_id = params[:field][:category_id]
    end




    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    def set_categories
      @categories = @field.center.categories.all
    end

    def set_centers
      @centers = Center.all 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:name, :description, :status, :center_id, :category_id)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_form.html.erb
<%= simple_form_for(@field) do |f| %>
  <%= f.error_notification %>




  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :status %>
  </div>

<% #if it's a new field, choose a center, if you edit the field, choose a category %>
<% if @field.new_record? %>
  <% if params[:center_id].present? %>
    <% @field.center_id = params[:center_id] %>
  <% end %>
  <div class="field">
    <%= f.label :center_id %></br>
    <%= f.collection_select(:center_id, @centers, :id, :name, :include_blank => "Choisir un centre") %>
  </div>
<%else%>
  <div class="field">
    <%= f.label :category %></br>
    <%= f.collection_select(:category_id, @categories, :id, :name, :include_blank => "Choisir une categorie") %>
  </div>
<%end%>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fields</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Centre</th>
      <th>Categorie</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.name %></td>
        <td><%= field.description %></td>
        <td><%= field.center.name %></td>
        <% unless field.category.nil? %>
        <td><%= field.category.name %></td>
        <% end %>
        <td><%= field.status %></td>
        <td><%= link_to 'Show', field %></td>
        <td><%= link_to 'Edit', edit_field_path(field) %></td>
        <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render 'form' %>

<%= link_to 'Back', fields_path %>

app/views/fields/show.html.erb
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @field.name %>
	</p>

	<p>
	  <strong>Description:</strong>
	  <%= @field.description %>
	</p>

	<p>
	  <strong>Status:</strong>
	  <%= @field.status %>
	</p>

	<p>
		<strong>Centre:</strong>
		<%= @field.center.name %>
	</p>

	<p>
		<% if @field.category.nil? %>
		<%= link_to 'Choisir une categorie', edit_field_path(@field) %>
		<% else %>
		<strong>Categorie:</strong>
		<%= @field.category.name %>
		<% end %>
	</p>

<table>
	<thead>
	<tr>
		<th>Jour</th>
		<th>Ouverture</th>
		<th>Fermeture</th>
		<th>Ouvert</th>
		<th>Edit</th>
	</tr>
	</thead>
	<tbody>
	<% @field.business_hours.each do |bh| %>
<tr>
	<td><%= bh.day %></td>
	<td><%= bh.start.strftime("%H:%M") %></td>
	<td><%= bh.end.strftime("%H:%M") %></td>
	<td><%= bh.open.to_s %></td>
	<td><%= link_to "Modifier", edit_business_hour_path(bh.id) %>	</td>
</tr>
	<%end%>
</tbody>
<table>
<p>	<%= link_to 'Créer business hour', new_business_hour_path(bh_id: @field.id, bh_type: @field.class.name) %></p>



	<%= link_to 'Edit', edit_field_path(@field) %> |
	<%= link_to 'Back', fields_path %>